verbatim:
  cabal-version: 3.0

name:                pdfname
version:             0.1.0
github:              "asr/pdfname"
license:             MIT
license-file:        LICENSE
author:              "Andrés Sicard-Ramírez"
maintainer:          "andres.sicard.ramirez@gmail.com"
copyright:           "Andrés Sicard-Ramírez"

extra-source-files:
- README.md
- CHANGELOG.md
- package.yaml
- stack-9.6.5.yaml

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/asr/pdfname#readme>

tested-with:
  GHC == { 9.6.5 }

dependencies:
- base     >= 4.9.1.0 && < 5
- filepath >= 1.4.1.1 && < 1.5

ghc-options:
- -Weverything
- -Werror
- -Wno-implicit-prelude
- -Wno-missing-safe-haskell-mode
- -Wno-all-missed-specialisations
- -Wno-prepositive-qualified-module
- -Wno-safe
- -Wno-unsafe

library:
  source-dirs: src
  dependencies:
  - directory >= 1.3.0.0 && < 1.4
  - optparse-applicative >= 0.18.1.0 && < 0.19
  - pdf-toolbox-document >= 0.1.2 && < 0.2
  - text >= 2.0.2 && < 2.1

executables:
  pdfname:
    main:                Main.hs
    source-dirs:         src/main
    dependencies:
    - optparse-applicative >= 0.18.1.0 && < 0.19
    - pdf-toolbox-core >= 0.1.1 && < 0.2
    - pdf-toolbox-document >= 0.1.2 && < 0.2
    - pdfname

tests:
  pdfname-test:
    main:                Tests.hs
    source-dirs:         test
    dependencies:
    - HUnit >= 1.6.0.0 && < 1.7
    - pdfname
    - tasty >= 1.4.2.1 && < 1.5
    - tasty-hunit >= 0.9.2 && < 0.11
    - tasty-silver >= 3.3.1.2 && < 3.4
    - text >= 2.0.2 && < 2.1
